### ISSUE TITLE
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.bluez.mesh.Network1

### ISSUE THREAD

**Issue by ddovnar** [SilvairGit/python-bluetooth-mesh#101]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 75, in run
    async with self:
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 325, in __aenter__
    await self.dbus_connect()
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 311, in dbus_connect
    await self.dbus_connected(owner)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 562, in dbus_connected
    self.network_interface = NetworkInterface(service)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/interfaces.py", line 317, in __init__
    self._interface = mesh_service.get_interface("org.bluez.mesh.Network1")
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/aio/proxy_object.py", line 159, in get_interface
    return super().get_interface(name)
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/proxy_object.py", line 216, in get_interface
    raise InterfaceNotFoundError(f'interface not found on this object: {name}')
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.bluez.mesh.Network1
```

**Comment by ddovnar** [comment]
Hi! Can anybody tell me reason of this error? Thanks

**Comment by przemyslawfierek-silvair** [comment]
Hi, did you start BlueZ with Bluetooth Mesh support?

**Comment by michallowasrzechonek-silvair** [comment]
Also, check that meshd found/attached itself to the adapter

**Comment by ddovnar** [comment]
```
● bluetooth-mesh.service - Bluetooth mesh service
   Loaded: loaded (/lib/systemd/system/bluetooth-mesh.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-02-22 07:26:47 GMT; 2h 21min ago
 Main PID: 989 (bluetooth-meshd)
    Tasks: 1 (limit: 3861)
   CGroup: /system.slice/bluetooth-mesh.service
           └─989 /usr/libexec/bluetooth/bluetooth-meshd

Feb 22 07:26:47 raspberrypi systemd[1]: Starting Bluetooth mesh service...
Feb 22 07:26:47 raspberrypi bluetooth-meshd[989]: D-Bus ready
Feb 22 07:26:47 raspberrypi bluetooth-meshd[989]: Request name success
Feb 22 07:26:47 raspberrypi bluetooth-meshd[989]: Loading node configuration from /var/lib/bluetooth/mesh
Feb 22 07:26:47 raspberrypi systemd[1]: Started Bluetooth mesh service.
Feb 22 07:26:47 raspberrypi bluetooth-meshd[989]: Controller hci 0 is in use

```

**Comment by przemyslawfierek-silvair** [comment]
`sudo hciconfig hci0 down; sudo ./bluetooth-meshd`

**Comment by ddovnar** [comment]
Is this information of "bluetooth-mesh service" can help?
bluetoothctl: 5.54
meshctl: 5.54

**Comment by ddovnar** [comment]
```
pi@raspberrypi:~/workspace/proj/pymesh $ systemctl status bluetooth-mesh.service 
● bluetooth-mesh.service - Bluetooth mesh service
   Loaded: loaded (/lib/systemd/system/bluetooth-mesh.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-02-22 10:22:59 GMT; 1min 42s ago
 Main PID: 3614 (bluetooth-meshd)
    Tasks: 1 (limit: 3861)
   CGroup: /system.slice/bluetooth-mesh.service
           └─3614 /usr/libexec/bluetooth/bluetooth-meshd

Feb 22 10:22:59 raspberrypi systemd[1]: Starting Bluetooth mesh service...
Feb 22 10:22:59 raspberrypi bluetooth-meshd[3614]: D-Bus ready
Feb 22 10:22:59 raspberrypi bluetooth-meshd[3614]: Request name success
Feb 22 10:22:59 raspberrypi bluetooth-meshd[3614]: Loading node configuration from /var/lib/bluetooth/mesh
Feb 22 10:22:59 raspberrypi bluetooth-meshd[3614]: Added Network Interface on /org/bluez/mesh
Feb 22 10:22:59 raspberrypi bluetooth-meshd[3614]: Hci dev 0000 removed
Feb 22 10:22:59 raspberrypi systemd[1]: Started Bluetooth mesh service.
pi@raspberrypi:~/workspace/proj/pymesh $ python3 main.py 
step1
hello
step3
init loop
runned...
SampleApplication
connecting...
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 77, in run
    await self.connect(addr=addr,iv_index=5)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 624, in connect
    configuration = await self.attach(self.token_ring.token, **kwargs)
TypeError: attach() got an unexpected keyword argument 'addr'

```

**Comment by ddovnar** [comment]
Now Bluetooth mesh service run correctly? But there is an error in application

**Comment by przemyslawfierek-silvair** [comment]
To keep this thread clean (to not solve many problems in one issue). Please create another issue with error above. Please check also if you are able to run any example application i.e. `meshcli`?

**Comment by ddovnar** [comment]
```
pi@raspberrypi:~/workspace/proj/pymesh $ systemctl status bluetooth-mesh.service 
● bluetooth-mesh.service - Bluetooth mesh service
   Loaded: loaded (/lib/systemd/system/bluetooth-mesh.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-02-22 10:17:12 GMT; 32min ago
 Main PID: 556 (bluetooth-meshd)
    Tasks: 1 (limit: 3861)
   CGroup: /system.slice/bluetooth-mesh.service
           └─556 /usr/libexec/bluetooth/bluetooth-meshd

Feb 22 10:17:11 raspberrypi systemd[1]: Starting Bluetooth mesh service...
Feb 22 10:17:12 raspberrypi bluetooth-meshd[556]: D-Bus ready
Feb 22 10:17:12 raspberrypi systemd[1]: Started Bluetooth mesh service.
Feb 22 10:17:12 raspberrypi bluetooth-meshd[556]: Request name success
Feb 22 10:17:12 raspberrypi bluetooth-meshd[556]: Loading node configuration from /var/lib/bluetooth/mesh
Feb 22 10:17:12 raspberrypi bluetooth-meshd[556]: Controller hci 0 is in use
pi@raspberrypi:~/workspace/proj/pymesh $ python3 main.py 
step1
hello
step3
init loop
runned...
SampleApplication
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/proxy_object.py", line 214, in get_interface
    intr_interface = next(i for i in self.introspection.interfaces if i.name == name)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 75, in run
    async with self:
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 325, in __aenter__
    await self.dbus_connect()
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 311, in dbus_connect
    await self.dbus_connected(owner)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 562, in dbus_connected
    self.network_interface = NetworkInterface(service)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/interfaces.py", line 317, in __init__
    self._interface = mesh_service.get_interface("org.bluez.mesh.Network1")
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/aio/proxy_object.py", line 159, in get_interface
    return super().get_interface(name)
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/proxy_object.py", line 216, in get_interface
    raise InterfaceNotFoundError(f'interface not found on this object: {name}')
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.bluez.mesh.Network1
pi@raspberrypi:~/workspace/proj/pymesh $ dbus-send --system --dest=org.bluez --print-reply / org.freedesktop.DBus.ObjectManager.GetManagedObjects | grep Network1
               string "org.bluez.Network1"

```

**Comment by ddovnar** [comment]
Service runned ok, error in application was disappear. But still can't get interface "mesh_service.get_interface("org.bluez.mesh.Network1")

**Comment by przemyslawfierek-silvair** [comment]
`Feb 22 10:17:12 raspberrypi bluetooth-meshd[556]: Controller hci 0 is in use` this line means that the BlueZ service is not attached to dongle (and in result D-Bus API is unavailable)

**Comment by QGB** [comment]
```
[update_manager.py:initialize()] - PackageDeploy: Using PackageKit Provider
[update_manager.py:initialize()] -
Initializing Client Updater: 'mainsail',
Channel: stable
path: /home/ubuntu/mainsail
[update_manager.py:_handle_auto_refresh()] - update_manger: Install validation pending, bypassing initial refresh
[machine.py:_check_service_file()] - Performing Service Validation...
[server.py:add_warning()] - Unable to retrieve Moonraker service info.  Service file must be updated manually.
[extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/ubuntu/printer_data/comms/moonraker.sock'
[server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: hi3798mv100
[app.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
[klippy_connection.py:_do_connect()] - Klippy Connection Established
[machine.py:extract_service_info()] - Error Extracting Service Info
Traceback (most recent call last):
  File "/home/ubuntu/moonraker-env/lib/python3.8/site-packages/dbus_next/proxy_object.py", line 217, in get_interface
    intr_interface = next(i for i in self.introspection.interfaces if i.name == name)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/moonraker/moonraker/components/machine.py", line 1209, in extract_service_info
    unit_intf, svc_intf = await self.dbus_mgr.get_interfaces(
  File "/home/ubuntu/moonraker/moonraker/components/dbus_manager.py", line 125, in get_interfaces
    intf = proxy_obj.get_interface(ifname)
  File "/home/ubuntu/moonraker-env/lib/python3.8/site-packages/dbus_next/aio/proxy_object.py", line 159, in get_interface
    return super().get_interface(name)
  File "/home/ubuntu/moonraker-env/lib/python3.8/site-packages/dbus_next/proxy_object.py", line 219, in get_interface
    raise InterfaceNotFoundError(f'interface not found on this object: {name}')
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.freedesktop.systemd1.Service
[server.py:add_log_rollover_item()] - Klipper Version: v0.11.0-123-g6b75f54e
[server.py:add_warning()] - file_manager: Klipper configuration file not located in 'config' folder.

Klipper Config Path: /home/ubuntu/klipper_config/printer.cfg

```
