### ISSUE TITLE
Application runs with error TypeError: attach() got an unexpected keyword argument 'addr'

### ISSUE THREAD

**Issue by ddovnar** [SilvairGit/python-bluetooth-mesh#102]
```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 77, in run
    await self.connect(addr=addr,iv_index=5)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh/application.py", line 624, in connect
    configuration = await self.attach(self.token_ring.token, **kwargs)
TypeError: attach() got an unexpected keyword argument 'addr'

```

**Comment by ddovnar** [comment]
``` python
   72  async def run(self, addr):
   73         print('runned...')
   74         print(type(self).__name__)
   75         async with self:
   76             print('connecting...')
   77             await self.connect(addr=addr,iv_index=5)
   78             #await self.connect()
   79             await self.configure()
   80             print('connected')
   81             client = self.elements[0][SensorClient]
   82             print('step2')
   83 
   84             for node in [0x0001,0x0002,0x0003,0x0004]:
   85                 await client.attention(node, app_index=0,attention=3)

```

**Comment by ddovnar** [comment]
Error solved by start process in sudo

**Comment by aeron169** [comment]
I have the same problem with sample application, i don't know what it means by the process, if it's the python application i'm using sudo and nothing seems to resolve the situation

I use the 8.6 since you've done  changes for 9.0 (with no docs so i guess it needs update)
