### ISSUE TITLE
interface not found on this object: org.bluez.Network1

### ISSUE THREAD

**Issue by ddovnar** [SilvairGit/python-bluetooth-mesh#103]
```
step1
hello
step3
init loop
runned...
SampleApplication
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/proxy_object.py", line 214, in get_interface
    intr_interface = next(i for i in self.introspection.interfaces if i.name == name)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 75, in run
    async with self:
  File "/usr/local/lib/python3.7/dist-packages/bluetooth_mesh/application.py", line 275, in __aenter__
    await self.dbus_connect()
  File "/usr/local/lib/python3.7/dist-packages/bluetooth_mesh/application.py", line 261, in dbus_connect
    await self.dbus_connected(owner)
  File "/usr/local/lib/python3.7/dist-packages/bluetooth_mesh/application.py", line 511, in dbus_connected
    self.network_interface = NetworkInterface(service)
  File "/usr/local/lib/python3.7/dist-packages/bluetooth_mesh/interfaces.py", line 317, in __init__
    self._interface = mesh_service.get_interface("org.bluez.Network1")
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/aio/proxy_object.py", line 159, in get_interface
    return super().get_interface(name)
  File "/usr/local/lib/python3.7/dist-packages/dbus_next/proxy_object.py", line 216, in get_interface
    raise InterfaceNotFoundError(f'interface not found on this object: {name}')
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.bluez.Network1
```

**Comment by ddovnar** [comment]
```
pi@raspberrypi:~/workspace/proj/pymesh $ sudo systemctl status bluetooth.service 
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-02-22 15:46:38 GMT; 32s ago
     Docs: man:bluetoothd(8)
 Main PID: 5008 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 3861)
   CGroup: /system.slice/bluetooth.service
           └─5008 /usr/libexec/bluetooth/bluetoothd -E -d

Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_version_complete() sending read supported commands command
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_version_complete() sending read index list command
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/rfkill.c:rfkill_event() RFKILL event idx 1 type 2 op 0 soft 0 hard 0
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_commands_complete() Number of commands: 65
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_commands_complete() Number of events: 35
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_commands_complete() enabling kernel-side connection control
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: src/adapter.c:read_index_list_complete() Number of controllers: 0
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: plugins/hostname.c:property_changed() static hostname: raspberrypi
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: plugins/hostname.c:property_changed() pretty hostname:
Feb 22 15:46:38 raspberrypi bluetoothd[5008]: plugins/hostname.c:property_changed() chassis:

```

**Comment by ddovnar** [comment]
How can I fix this interface "org.bluez.Network1"?

**Comment by michallowasrzechonek-silvair** [comment]
You are running bluetoothd, not bluetooth-meshd. Please consult bluez documentation, specifically mesh-api.txt. This library is just a pretty thin wrapper around that.
