### ISSUE TITLE
Instructions how to use skeleton.py

### ISSUE THREAD

**Issue by Carmis** [SilvairGit/python-bluetooth-mesh#54]
When using v0.2.15 together with Bluez 5.54 the skeleton.py example don't work out of the box.
Using the docs and the API I can't figure out what the problem is the output when running the sample application is the following:
```
DEBUG:SampleApplication:Connecting to D-Bus
INFO:SampleApplication:Connecting to org.bluez.mesh
INFO:SampleApplication:Registering application
INFO:SampleApplication:Attach 0
ERROR:SampleApplication:Attach failed: Object not found, trying to import node
WARNING:SampleApplication:Import 2b74a779-1243-551f-8814-2ad279ceec14
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/application.py", line 564, in connect
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/application.py", line 736, in attach
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/interfaces.py", line 296, in attach
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/aio/proxy_object.py", line 79, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/proxy_object.py", line 59, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Object not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docs/skeleton.py", line 113, in <module>
    main()
  File "docs/skeleton.py", line 109, in main
    loop.run_until_complete(app.run(addr))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "docs/skeleton.py", line 76, in run
    await self.connect(addr=addr, iv_index=5)
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/application.py", line 577, in connect
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/application.py", line 786, in import_node
  File "/home/pi/.local/lib/python3.7/site-packages/bluetooth_mesh-0.2.15-py3.7.egg/bluetooth_mesh/interfaces.py", line 334, in import_node
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/aio/proxy_object.py", line 77, in method_fn
    body=list(args)))
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/aio/message_bus.py", line 241, in call
    self._call(msg, reply_handler)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/message_bus.py", line 514, in _call
    self.send(msg)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/aio/message_bus.py", line 256, in send
    asyncio.ensure_future(self._loop.sock_sendall(self._sock, msg._marshall()))
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/message.py", line 206, in _marshall
    body_block = Marshaller(self.signature, self.body)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/_private/marshaller.py", line 8, in __init__
    self.signature_tree.verify(body)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/signature.py", line 331, in verify
    type_.verify(body[i])
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/signature.py", line 248, in verify
    self._verify_uint16(body)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/signature.py", line 128, in _verify_uint16
    f'DBus UINT16 type "q" must be between {UINT16_MIN} and {UINT16_MAX}')
dbus_next.errors.SignatureBodyMismatchError: DBus UINT16 type "q" must be between 0 and 65535
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=EOFError()>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/aio/message_bus.py", line 281, in _message_reader
    if self._unmarshaller.unmarshall():
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/_private/unmarshaller.py", line 255, in unmarshall
    self._unmarshall()
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/_private/unmarshaller.py", line 198, in _unmarshall
    self.endian = self.read_byte()
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/_private/unmarshaller.py", line 70, in read_byte
    return self.read(1)[0]
  File "/home/pi/.local/lib/python3.7/site-packages/dbus_next/_private/unmarshaller.py", line 53, in read
    raise EOFError()
EOFError
```
After digging around a bit it seems like version 5.54 of Bluez has not implemented JoinComplete in the API but this package expect it from v0.2.8, is this correct? It is unfortunate that the available version of this package expects unreleased code of Bluez if that is the case.

**Comment by michallowasrzechonek-silvair** [comment]
That's correct. The mesh part of BlueZ is still in development, API is evolving, and in general: YMMV. I strongly recommend using the latest master, we try to follow upstream as quickly as we can.

I don't know if/when bluetooth-meshd is going to be released as stable.

**Comment by Carmis** [comment]
Ok good to know, my first impression was that it was more stable.
I started using the latest master and now it works really smooth.
