### ISSUE TITLE
Unable to create network

### ISSUE THREAD

**Issue by PeachBug** [SilvairGit/python-bluetooth-mesh#94]
Hi there,

I'm trying to create and configure a small BLE mesh network using your library. But, org.Bluez.mesh.Network1.CreateNetwork is returning "Operation failed".  Am I missing something in my application code?

![bustle](https://user-images.githubusercontent.com/33940272/104757189-a5796d80-5754-11eb-9d29-0e63aef046b4.png)

code:
```
#!/usr/bin/env python3

import sys
import asyncio
from contextlib import suppress

sys.path.append('bluetooth_mesh')
from bluetooth_mesh.application import Application

logger = logging.getLogger()

class meshApp(Application):

    async def run(self):
        async with self:
            await self.create_network()

def main():
    
    loop = asyncio.get_event_loop()
    app = meshApp(loop)

    with suppress(KeyboardInterrupt):
        loop.run_until_complete(app.run())

if __name__ == '__main__':
    main()
```

log:
```
DEBUG    Using selector: EpollSelector
DEBUG    Connecting to D-Bus
INFO     Connecting to org.bluez.mesh
INFO     Registering application
INFO     Create 5853cc95-8f56-5a85-9381-863fbf8d78d5
INFO     Unregistering application
Traceback (most recent call last):
  File "prov.py", line 34, in <module>
    main()
  File "prov.py", line 25, in main
    loop.run_until_complete(app.run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "prov.py", line 17, in run
    await self.create_network()
  File "/home/dev/mesh/silvairlib/bluetooth_mesh/application.py", line 767, in create_network
    await self.network_interface.create_network("/", self.uuid)
  File "/home/dev/mesh/silvairlib/bluetooth_mesh/interfaces.py", line 383, in create_network
    return await self._interface.call_create_network(app_root, uuid.bytes)
  File "/home/dev/.local/lib/python3.8/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/home/dev/.local/lib/python3.8/site-packages/dbus_next/proxy_object.py", line 61, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Operation failed
```

**Comment by michallowasrzechonek-silvair** [comment]
I think you need to declare at least one element via `Application.ELEMENTS`

**Comment by PeachBug** [comment]
Yes, it was the fact of having no ELEMENTS in the Application. Thanks! Just one more question, any special reason for using "/" as app_root instead of self.path on self.network_interface.create_network()? This was my initial guess, when create_network failed, but then I changed and the problem remained.

Note: The Application.PATH has already "/com/silvair/application" as default in the library.

**Comment by michallowasrzechonek-silvair** [comment]
No particular reason, it's a design choice. Your application might expose one DBus API towards bluez and another one for the rest of the world. Bluez doesn't have any particular requirements, as long as your objects provide necessary interfaces.
